#!/bin/bash

ref=$1
asm=$2
output=$3

if [ -ne ${ref}.bwt ]; then
    bwa index ${ref}
fi

bwa mem ${ref} ${asm} | samtools view -b > ${output}.bam

samtools sort -O bam -T ${output} ${output}.bam > ${output}.sorted.bam

samtools index ${output}.sorted.bam
